<p>
	In addition to each domain-specific Compara database, a pan-taxonomic Compara is built for each release using representative genomes from 
	all significant clades represented in 
	<a href='http://www.ensembl.org'>Ensembl</a> and
	<a href='http://www.ensemblgenomes.org'>EnsemblGenomes</a>, to offer 
	a broad view of homologous relationships from across the taxonomy.
	The species tree used is a combination of 
	<a href='http://www.ensembl.org/info/genome/compara/index.html'>Ensembl's	
	taxonomy based tree</a> and a manually calculated tree for bacteria. The species
used are listed on the <a href="http://ensemblgenomes.org/info/species/pan-compara">EnsemblGenomes website</a> and in this documentation: <a href="/info/genome/compara/homology_method.html#species">Gene Orthology/Paralogy prediction method: Species Used</a>.
</p>
