#!/usr/bin/env perl

=head1 LICENSE

Copyright [1999-2015] Wellcome Trust Sanger Institute and the EMBL-European Bioinformatics Institute
Copyright [2016-2017] EMBL-European Bioinformatics Institute

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

=cut

# Server before start hook for EG. This script will be "required" in start_server script at ensembl-webcode:
# https://github.com/Ensembl/ensembl-webcode/blob/release/87/ctrl_scripts/start_server#L128
#
# This script sets an environment variable so that the httpd.conf at eg-web-common can locate the one in ensembl-webcode:
# https://github.com/EnsemblGenomes/eg-web-common/commit/ea06e813d7b5944c066dc7bc21e5b278f26a9bfc 
    
use strict;
use warnings;

use File::Basename;
use Cwd qw(abs_path);

my $web_root = abs_path(dirname (__FILE__) . "/../../ensembl-webcode");

$ENV{ENV_ENSEMBL_WEBROOT} = $web_root;

1;
