<h2 class="first">Forthcoming training courses</h2>
<ul>
<li>
<h3>transPLANT user training workshop</h3>
<p>The workshop will focus on triticeae (mostly wheat and barley) data resources and tools, and will include tutorials on data access and use from INRA, EMBL-EBI, IPK and MIPS. This workshop is targeted at experimental biologists, breeders, bio-informaticians, and all other data users as no prior informatics knowledge or skills are required. More information is available <a href="http://transplantdb.eu/node/1796">here</a>.</p>
</li>
</ul>