<span id="ebi_logo"> 	  
<p>
Ensembl Genomes is developed by <a href="https://www.ebi.ac.uk">EMBL-EBI</a> and is powered by <a href="https://www.ensembl.org">Ensembl</a> software system for the analysis and visualisation of genomic data. For details of our funding please <a href="/info/about/credits.html">click here</a>.
</p>
<p>
<a href="https://www.ebi.ac.uk/"> <img align="absmiddle" src="/img/ebi_logo.png" /></a> 
<a style="padding-left:20px" href="https://www.ensembl.org"><img align="absmiddle" src="/img/empowered.png" /></a>
</p>
</span>
