<h2 class="first"><a title="Ensembl Genomes" href="http://ensemblgenomes.org/">Ensembl Genomes</a></h2>
<p>The Ensembl Genomes project produces genome databases for important species from across the taxonomic range, using the Ensembl software system. Five sites are now available: <a href="http://bacteria.ensembl.org">Ensembl Bacteria</a>, <a href="http://protists.ensembl.org">Ensembl Protists</a>, <a href="http://metazoa.ensembl.org">Ensembl Metazoa</a>, <a href="http://plants.ensembl.org">Ensembl Plants</a> and <a href="http://fungi.ensembl.org">Ensembl Fungi</a>. These new sites complement the existing <a href="http://www.ensembl.org">Ensembl</a> site, with its focus on vertebrate genomes. You can search all Ensembl and Ensembl Genomes databases from the search bar in the top right of this page.</p>
<p>Ensembl Genomes data is available through many of the same routes as Ensembl data. Data can be accessed via:</p>
<ul>
<li>this web browser</li> 
<li><a href="/biomart/martview/">BioMarts</a> (query optimised data warehouses) constructed for each of the Ensembl Genomes site</li.s
<li> via FTP (<a href="http://ftp.ensemblgenomes.org/pub">ftp.ensemblgenomes.org/pub</a>) </li>
<li>via the Ensembl Genomes public mysql server (mysql.ebi.ac.uk:4157:anonymous). </li>
<li>using the <a href="/info/data/api.html">Ensembl API</a>.</li>
</ul>
<p>The API has been modified slightly to support the existence of "genome collections", i.e. the existence of many small genomes in a single Ensembl database (a model which has been adopted for Ensembl Bacteria).  The API makes the use of multi-genome databases transparent to users interested in a single genome, while methods to access a traditional, single-genome database, are unchanged. We aim to keep Ensembl Genomes software in sync with software releases of Ensembl, to ensure that users can access databases from across the taxonomic range using the same software.</p>
<p>See the <a href="/info/index.html">documentation</a> for more information about how to use Ensembl Genomes.</p>
<p><a href="http://www.ensembl.org/info/about/index.html"><img src="http://www.ensembl.org/img/empowered.png" alt="Powered by Ensembl" /></a></p>
